language: php
os: linux

php: 7.1
env: ILLUMINATE_VERSION=5.1.*

jobs:
  include:
    - stage: validate
      script: ./vendor/bin/phpunit --testsuite=Integration --verbose
      after_script: skip
    - stage: test
      env: ILLUMINATE_VERSION=5.1.*
    - stage: test
      env: ILLUMINATE_VERSION=5.2.*
    - stage: test
      env: ILLUMINATE_VERSION=5.3.*
    - stage: test
      env: ILLUMINATE_VERSION=5.4.*
    - stage: test
      env: ILLUMINATE_VERSION=5.5.*
    - stage: test
      env: ILLUMINATE_VERSION=5.6.*
    - stage: test
      env: ILLUMINATE_VERSION=5.7.*
    - stage: test
      env: ILLUMINATE_VERSION=5.8.*
    - stage: test
      php: 7.2
      env: ILLUMINATE_VERSION=6.*

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer require laravel/framework:"${ILLUMINATE_VERSION}" --dev --no-update

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover --testsuite=Unit --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
